backend/controllers/ImageController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\ImageSearch;
use common\models\Image;
use common\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


/**
 * ImageController implements the CRUD actions for Image model.
 */
class ImageController extends Controller
{



    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'], @ todo ajaxal
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_ADMIN],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Image models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ImageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if (!empty(Yii::$app->request->get("fromImageAttachWidget"))) {
            if ((int)Yii::$app->request->get("fromImageAttachWidget") === 1) {
                $this->layout = "main_no_sidebar";
                Yii::$app->view->params['disable_align_items_center'] = true;
                Yii::$app->view->params['disable_header_footer'] = true;
            }
        };

        if(!empty(Yii::$app->request->get('CKEditor'))){
            $this->layout = "modal";
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Deletes an existing Image model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Image model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Image the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Image::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use backend\assets\LimitlessAsset;
use yii\widgets\Menu;
use common\models\User;

LimitlessAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<!-- Main navbar -->
<div class="navbar navbar-expand-md navbar-dark">
    <div class="navbar-brand">

        <ul class="navbar-nav" style="margin-left:0;position:absolute;left:0;">
            <li class="nav-item">
                <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                    <i class="icon-paragraph-justify3"></i>
                </a>
            </li>
        </ul>

        <a href="<?=Yii::$app->homeUrl?>" class="d-inline-block" style="margin-left:30px;">
            <img src="/img/eholtosag-logo.png" alt="">
        </a>
    </div>

    <div class="d-md-none">
        <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>-->
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-mobile">


        <span class="navbar-text ml-md-3 mr-md-auto">
        </span>

        <ul class="navbar-nav">
            <li class="nav-item dropdown dropdown-user">
                <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-user rounded-circle"></i>
                    <span><?php echo Yii::$app->user->isGuest? 'Vendég': Yii::$app->user->identity->username ?></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                    <?php
                    echo Html::beginForm(['/site/logout'], 'post')
                        . Html::submitButton(
                            '<i class="icon-switch2"></i> Logout',
                            ['class' => 'dropdown-item']
                        )
                        . Html::endForm();
                    ?>
                </div>
            </li>
        </ul>
    </div>
</div>
<!-- /main navbar -->
<div class="page-content">

    <div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">
        <!-- Sidebar mobile toggler -->
        <div class="sidebar-mobile-toggler text-center">
            <a href="#" class="sidebar-mobile-main-toggle">
                <i class="icon-arrow-left8"></i>
            </a>
            Navigation
            <a href="#" class="sidebar-mobile-expand">
                <i class="icon-screen-full"></i>
                <i class="icon-screen-normal"></i>
            </a>
        </div>
        <!-- /sidebar mobile toggler -->

        <!-- Main navigation -->
        <div class="card card-sidebar-mobile">
            <?=Menu::widget([
                'items' => [
                    [
                        'label' => '<i class="icon-magazine"></i><span>Hírek, exkluzív tartalmak</span>',
                        'url' => ['/article/index'],
                        'visible' => Yii::$app->user->can(User::ROLE_ADMIN)
                    ],
                    [
                        'label' => '<i class="icon-file-picture"></i><span>Képek</span>',
                        'url' => ['/image/index'],
                        'visible' => Yii::$app->user->can(User::ROLE_ADMIN)
                    ],
                    [
                        'label' => '<i class="icon-user"></i><span>Felhasználók</span>',
                        'url' => '/admin/user/index',
                        'visible' => Yii::$app->user->can(User::ROLE_ADMIN)
                    ],
                    [
                        'label' => '<i class="icon-mail5"></i><span>Meghívó küldése</span>',
                        'url' => '/admin/user/invite',
                        'visible' => Yii::$app->user->can(User::ROLE_ADMIN)
                    ],
                    [
                        'label' => '<i class="icon-user-lock"></i><span>Adminisztrátorok</span>',
                        'url' => ['/adminuser/adminindex'],
                        'visible' => Yii::$app->user->can(User::ROLE_ADMIN)
                    ],
                ],
                'activeCssClass'=>'active nav-item-expanded nav-item-open',
                'encodeLabels' => false,
                'options' => [
                    'class' => 'nav nav-sidebar',
                    'data-nav-type' => 'accordion'
                ],
                'submenuTemplate' => "\n<ul class='nav nav-group-sub'>\n{items}\n</ul>\n",
                'linkTemplate' => '<a href="{url}" class="nav-link">{label}</a>',
                'itemOptions'=>array('class'=>'nav-item'),
                'activateParents'=>true,
            ]);?>
        </div>

    </div>

    <div class="content-wrapper">
        <?= $content ?>
    </div>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main_no_sidebar.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use backend\assets\LimitlessAsset;

LimitlessAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<?php
$disableBackground = false;
if (isset($this->params['disable_background']) && $this->params['disable_background'] === true) {
    $disableBackground = true;
}

?>
<body class="<?= ($disableBackground?"no-background":"") ?>">
<?php $this->beginBody() ?>

<?php
$disableHeaderFooter = true;
if (!isset($this->params['disable_header_footer'])) {
    $disableHeaderFooter = false;
?>
    
    <div class="navbar navbar-expand-md navbar-dark">

        <div class="navbar-brand">
            <a href="/" class="d-inline-block">
                <img src="/img/eholtosag-logo.png" alt="">
            </a>
        </div>

    </div>

<?php
}
?>

<div class="page-content">
    <?php
    /*
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'About', 'url' => ['/site/about']],
        ['label' => 'Contact', 'url' => ['/site/contact']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    */
    ?>

    <div class="content-wrapper">
        <div class="<?= ($disableHeaderFooter === false ? "content" : "")?> d-flex justify-content-center <?= (isset($this->params['disable_align_items_center'])&&$this->params['disable_align_items_center']===true ? "" : "align-items-center") ?>">
            <?= $content ?>
        </div>

        <?php
        if (!isset($this->params['disable_header_footer'])) {
            ?>
            <div class="navbar navbar-expand-lg navbar-light">
                <div class="navbar-collapse collapse" id="navbar-footer">
                <span class="navbar-text">
                    &copy; Éholtóság <?= date('Y') ?>
                </span>
                </div>
            </div>
            <?php
        }
        ?>


    </div>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/modal.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use backend\assets\LimitlessAsset;
use yii\widgets\Menu;
use common\models\User;

LimitlessAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<!-- /main navbar -->
<div class="page-content">

    <div class="content-wrapper">
        <?= $content ?>
    </div>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>